name: Exploring variables and secrtes
on: push
jobs:
    docker:
        runs-on: ubuntu-latestt
        steps:
          - name: Docker Build
            run: docker build -t ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/imageName:latest
        
          - name: Docker login
            run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

          - name: Docker publish
            run: docker push ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ IMAGE_NAME }}:latest
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
          - name: Docker Run
            run: docker run -d -p 8080:80 ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ IMAGE_NAME }}:latest

